# Site information
site_name: NE30104
site_url: https://liyangxia.com
copyright: Copyright &copy; 2025 liyangxia.com

# Site theme configuration
theme:
  name: material
  custom_dir: overrides

  language: en

  icon:
    logo: material/bash

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.indexes
    - toc.integrate

extra:
  homepage: /

extra_javascript:
  - javascripts/flag.js

plugins:
  - blog:
      post_date_format: medium
      post_url_date_format: yyyy
      post_url_format: "{slug}"
      post_slugify_separator: _
      post_excerpt: required
      post_excerpt_max_authors: 0
      post_excerpt_max_categories: 1
      post_readtime: true
      post_readtime_words_per_minute: 300
      archive: true
      archive_name: Archive
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy
      archive_url_format: "{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "{slug}"
      categories_slugify_separator: _
      pagination: false


nav:
  - index.md
  - Blog:
    - blog/index.md
